### ISSUE TITLE
No need to have PendingClose place state

### ISSUE THREAD

**Issue by avahan** [open-autonomy/spot#4]
While implementing LastMileDispatching and state machine it became clear, that there is no need in separate state for place as PendingClose.
In any case there will be two states to analyze:
For Spot: PlaceState + SpotState
For Queue: PlaceState + QueueState

So everyone receiving those will be able to determine on their own, that place is pending close, if PlaceState is Closed, but there is still some activity (i.e. Full or Reserved). There is no need in explicit state to indicate that.

**Comment by politick** [comment]
Yes you're right.  This is an artefact from when the `spot` state and `user control` states were in a single state machine.

As far as the user, it's either open, closed or deleted. 
The Pending delete is meaningful for the user, but as you've stated pending close is redundant in this state machine.
